# Generated by Django 6.0.6 on 2026-06-29 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_featureflag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreferenciaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mostrar_estadisticas', models.BooleanField(default=True, verbose_name='Mostrar estadísticas en la pantalla principal')),
                ('mostrar_sugerencias', models.BooleanField(default=True, verbose_name='Mostrar sugerencias de productos')),
                ('confirmar_vaciar_lista', models.BooleanField(default=True, verbose_name='Pedir confirmación antes de vaciar la lista')),
                ('agrupar_por_pasillos', models.BooleanField(default=True, verbose_name='Agrupar productos por pasillos')),
                ('marcar_done_al_tocar', models.BooleanField(default=False, verbose_name='Marcar producto como cogido con un solo toque')),
                ('recordatorio_semanal', models.BooleanField(default=False, verbose_name='Recordatorio semanal de la compra')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preferencias', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Preferencia de usuario',
                'verbose_name_plural': 'Preferencias de usuarios',
            },
        ),
    ]
