# Generated by Django 6.0.6 on 2026-06-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_preferenciausuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciausuario',
            name='onboarding_completado',
            field=models.BooleanField(default=False, verbose_name='Ha visto la guía de bienvenida'),
        ),
    ]
