# Generated by Django 6.0.6 on 2026-08-08 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_preferenciausuario_onboarding_completado'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntentoFallo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.CharField(max_length=255, unique=True)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('ultimo_intento', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Intento fallido',
                'verbose_name_plural': 'Intentos fallidos',
                'ordering': ['-ultimo_intento'],
            },
        ),
    ]
