# Generated by Django 6.0.7 on 2026-08-10 18:44

from django.db import migrations, models


def transferir_solo_superusuarios(apps, schema_editor):
    """Los flags que antes solo veían los superusuarios pasan a ser premium."""
    FeatureFlag = apps.get_model('usuarios', 'FeatureFlag')
    FeatureFlag.objects.filter(solo_superusuarios=True).update(requiere_premium=True)


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_intentofallo'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureflag',
            name='requiere_premium',
            field=models.BooleanField(default=False, help_text='Si está marcado, solo lo usan los usuarios con plan premium (el superusuario no tiene ventajas: también necesita premium)'),
        ),
        migrations.RunPython(
            transferir_solo_superusuarios,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='featureflag',
            name='solo_superusuarios',
        ),
        migrations.AddField(
            model_name='usuario',
            name='premium_hasta',
            field=models.DateTimeField(blank=True, help_text='Fecha en la que caduca el plan premium. Vacío o pasado = plan básico. El superusuario NO tiene ventajas automáticas: también se le aplica su plan.', null=True, verbose_name='Premium hasta'),
        ),
    ]
