# Generated by Django 6.0.6 on 2026-06-29 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasillo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Pasillo',
                'verbose_name_plural': 'Pasillos',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Lista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lista',
                'verbose_name_plural': 'Listas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ListaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('en_carro', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='compra.lista')),
                ('pasillo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='compra.pasillo')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': [models.OrderBy(models.F('pasillo__orden'), nulls_last=True), 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Supermercado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supermercados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supermercado',
                'verbose_name_plural': 'Supermercados',
                'ordering': ['nombre'],
                'unique_together': {('usuario', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='pasillo',
            name='supermercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasillos', to='compra.supermercado'),
        ),
        migrations.AddField(
            model_name='lista',
            name='supermercado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas', to='compra.supermercado'),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
                ('pasillo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='compra.pasillo')),
            ],
            options={
                'verbose_name': 'Palabra clave',
                'verbose_name_plural': 'Palabras clave',
                'unique_together': {('pasillo', 'palabra')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pasillo',
            unique_together={('supermercado', 'orden')},
        ),
    ]
