# Generated by Django 6.0.6 on 2026-06-30 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='es_plantilla',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lista',
            name='nombre_plantilla',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
