# Generated by Django 6.0.6 on 2026-08-06 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_lista_es_plantilla_lista_nombre_plantilla'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='keyword',
            options={'ordering': ['palabra'], 'verbose_name': 'Palabra clave', 'verbose_name_plural': 'Palabras clave'},
        ),
    ]
