# Generated by Django 6.0.6 on 2026-08-07 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_supermercado_fecha_publicacion_supermercado_likes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='pasillo',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='pasillos', to='compra.categoria'),
        ),
        migrations.CreateModel(
            name='CategoriaKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=100)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='keywords', to='compra.categoria')),
            ],
            options={
                'verbose_name': 'Palabra clave de categoría',
                'verbose_name_plural': 'Palabras clave de categoría',
                'ordering': ['palabra'],
                'unique_together': {('categoria', 'palabra')},
            },
        ),
    ]
