# Generated by Django 6.0.7 on 2026-08-10 15:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_categoria_pasillo_categorias_categoriakeyword'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='lista',
            index=models.Index(fields=['usuario', '-fecha'], name='lista_usuario_fecha_idx'),
        ),
    ]
