"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_bootstrap5',
    'compra',
    'usuarios',
]

JAZZMIN_SETTINGS = {
    "site_title": "Compra Inteligente",
    "site_header": "🛒 Compra Inteligente",
    "site_brand": "🛒 Compra",
    "welcome_sign": "Bienvenido al panel de control",
    "copyright": "Compra Inteligente",

    # Iconos para cada modelo
    "icons": {
        "compra.Supermercado": "fas fa-store",
        "compra.Pasillo": "fas fa-map-signs",
        "compra.Keyword": "fas fa-tags",
        "compra.Lista": "fas fa-shopping-cart",
        "compra.ListaItem": "fas fa-check-square",
        "auth.User": "fas fa-user",
        "auth.Group": "fas fa-users",
    },

    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",

    # Ocultar modelos que no necesitas ver habitualmente
    "hide_models": ["auth.Group"],

    # Menú lateral personalizado
    "order_with_respect_to": [
        "compra.Lista",
        "compra.ListaItem",
        "compra.Supermercado",
        "compra.Pasillo",
        "compra.Keyword",
    ],

}

JAZZMIN_UI_TWEAKS = {
    "navbar": "navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-teal",
    "accent": "accent-info",
    "brand_colour": "navbar-dark",
    "theme": "cyborg",
    "dark_mode_theme": "cyborg",
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'usuarios.middleware.ContentSecurityPolicyMiddleware',
    'usuarios.middleware.AdminLoginRateLimitMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'usuarios.context_processors.flags',

            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
        # Reutilizar la conexión entre peticiones en vez de abrir/cerrar
        # una por request (gran ahorro de handshake TCP+auth).
        'CONN_MAX_AGE': 300,
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'Europe/Madrid'

USE_I18N = True

USE_TZ = True

TEMPLATES[0]['DIRS'] = [BASE_DIR / 'templates']


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
AUTH_USER_MODEL = 'usuarios.Usuario'
LOGIN_URL = 'usuarios:login'
LOGIN_REDIRECT_URL = 'compra:lista'
LOGOUT_REDIRECT_URL = 'usuarios:login'
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# IA
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY')

# Proxies de confianza (p.ej. nginx) que reenvían X-Forwarded-For.
# Vacío = sin proxy: se usa REMOTE_ADDR, que el cliente no puede falsificar.
TRUSTED_PROXIES = [p.strip() for p in os.getenv('TRUSTED_PROXIES', '').split(',') if p.strip()]

# Cuando la app va detrás de un proxy TLS (HTTPS), se confía en
# X-Forwarded-For aunque el proxy no esté en TRUSTED_PROXIES. Desactivar
# solo si la app pudiera recibir peticiones directas sin proxy (ahí un
# X-Forwarded-Proto: https falso permitiría suplantar la IP y saltarse
# los rate limits). En local/LAN (HTTP) no tiene efecto.
CONFIAR_XFF_EN_HTTPS = os.getenv('CONFIAR_XFF_EN_HTTPS', 'True') == 'True'

# Límites de tamaño de subidas/body: protegen frente a DoS por payloads
# gigantes. Las fotos se validan además en redimensionar_imagen (15MB) y con
# un rechazo temprano por Content-Length en analizar_foto (16MB).
DATA_UPLOAD_MAX_MEMORY_SIZE = 16 * 1024 * 1024
FILE_UPLOAD_MAX_MEMORY_SIZE = 16 * 1024 * 1024


# Seguridad de transporte (HTTPS)
# -------------------------------------
# Cuando la app se sirve por HTTPS (producción) se fuerzan cookies seguras,
# redirección a HTTPS, HSTS y política de referer. En local (DEBUG=True)
# se deja HTTP para no romper el acceso por red local/Meshnet.
# ENABLE_HTTPS=True lo fuerza siempre; ENABLE_HTTPS=False lo desactiva.
_https = os.getenv('ENABLE_HTTPS')
if _https == 'True' or (_https is None and not DEBUG):
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_REFERRER_POLICY = 'same-origin'

# Expiración de sesión por inactividad (por defecto Django usa 2 semanas;
# si se quiere cerrar sesión al cerrar el navegador, descomentar):
# SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Alertas de errores por email (ADMINS) ante 500 en producción.
# Formato de ADMINS: "Nombre:correo@dominio,Nombre2:correo2@dominio"
# Sin credenciales SMTP configuradas, el backend cae al de consola y no se
# envía nada (todo degrada sin romper).
ADMINS = [
    tuple(a.split(':', 1)) for a in os.getenv('ADMINS', '').split(',')
    if ':' in a and a.strip()
]
SERVER_EMAIL = os.getenv('SERVER_EMAIL', 'errores@comprainteligente.local')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', SERVER_EMAIL)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
if EMAIL_HOST_USER:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# Caducidad del enlace de activación de cuenta: 24 horas.
PASSWORD_RESET_TIMEOUT = 60 * 60 * 24

# Content-Security-Policy (ver usuarios/middleware.py:ContentSecurityPolicyMiddleware).
# Pragmática: se permiten scripts/estilos inline (las plantillas usan JS/CSS
# inline y atributos style/onclick) y el CDN de Bootstrap; se bloquean el resto
# de orígenes externos, iframes, objetos/plugins y la navegación a sitios ajenos.
CSP_HEADER = (
    "default-src 'self'; "
    "script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
    "style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; "
    "img-src 'self' data: blob: https://cdn.jsdelivr.net; "
    "font-src 'self' data: https://cdn.jsdelivr.net; "
    "connect-src 'self'; "
    "object-src 'none'; "
    "base-uri 'self'; "
    "form-action 'self'; "
    "frame-src 'self'; "
    "frame-ancestors 'none'; "
)

# Dominios de correo temporal/descartable rechazados en el registro.
# La verificación por email es la capa real de seguridad; esta lista es solo
# un primer filtro (se amplía a mano cuando aparezcan dominios nuevos).
DOMINIOS_TEMPORALES = {
    'dnsink.com',
    'mailinator.com',
    'mailinator.net',
    '10minutemail.com',
    '10minutemail.net',
    'guerrillamail.com',
    'guerrillamail.net',
    'grr.la',
    'tempmail.com',
    'tempmail.net',
    'temp-mail.org',
    'yopmail.com',
    'yopmail.net',
    'trashmail.com',
    'trashmail.net',
    'mailnator.com',
    'dispostable.com',
    'throwawaymail.com',
    'maildrop.cc',
    'getnada.com',
    'inboxkitten.com',
    'sharklasers.com',
}

# Logging: consola (docker logs) + archivo rotatorio (./logs/django.log).
# Si hay SMTP configurado, los errores 500 se avisan por email a ADMINS.
LOG_DIR = BASE_DIR / 'logs'
LOG_DIR.mkdir(parents=True, exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {message}',
            'style': '{',
        },
    },
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'archivo': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOG_DIR / 'django.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'mail_admins': {
            'class': 'django.utils.log.AdminEmailHandler',
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'include_html': False,
        },
    },
    'root': {
        'handlers': ['console', 'archivo'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'archivo'],
            'level': 'INFO',
            'propagate': False,
        },
        'django.request': {
            'handlers': (
                ['console', 'archivo', 'mail_admins']
                if EMAIL_HOST_USER else ['console', 'archivo']
            ),
            'level': 'ERROR',
            'propagate': False,
        },
        'compra': {
            'handlers': ['console', 'archivo'],
            'level': 'INFO',
            'propagate': False,
        },
        'usuarios': {
            'handlers': ['console', 'archivo'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}
